[package]
name = "maki-remote"
version.workspace = true
edition.workspace = true

[dependencies]
maki-agent = { workspace = true }
maki-config = { workspace = true }
arc-swap = { workspace = true }
base64 = { workspace = true }
flume = { workspace = true }
fast_qr = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tiny_http = { workspace = true }
tracing = { workspace = true }
tungstenite = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }