//! AppArmor interop.
//!
//! With `kernel.apparmor_restrict_unprivileged_userns=1`, AppArmor moves an
//! unconfined process into the `unprivileged_userns` profile the moment it
//! calls `unshare(CLONE_NEWUSER)`. That profile allows
//! the `unshare` but denies every capability, so `unshare(CLONE_NEWNS)`,
//! `mount` and `pivot_root` inside the new namespace all return EPERM and the
//! sandbox cannot build a filesystem.
//!
//! The sysctl is not the lever. `bwrap` runs fine with it left at `1` because
//! the distro ships `/etc/apparmor.d/bwrap-userns-restrict`, a profile for the
//! `bwrap` binary that grants `userns`, `capability` and `mount`. This module
//! inspects the state and renders the equivalent profile for maki.

use std::path::{Path, PathBuf};

/// Where the kernel reports the AppArmor confinement of the calling process,
/// e.g. `unprivileged_userns (enforce)`.
const ATTR_CURRENT: &str = "/proc/self/attr/current";

/// Profile AppArmor moves an unconfined process into on user namespace
/// creation while the restriction is armed.
const USERNS_PROFILE: &str = "unprivileged_userns";

/// Arms the restriction above. Its value says the restriction is possible,
/// never that it is what blocked us.
const RESTRICT_USERNS_SYSCTL: &str = "/proc/sys/kernel/apparmor_restrict_unprivileged_userns";

/// Name of the profile to install, and where it belongs on disk.
const PROFILE_NAME: &str = "maki-sandbox";
const PROFILE_PATH: &str = "/etc/apparmor.d/maki-sandbox";

/// Sibling entry points that can spawn a sandbox, beside the running binary.
const SANDBOX_ENTRY_POINTS: &[&str] = &["maki", "sandbox-shell", "sandbox-diag"];

/// The AppArmor profile confining this process, without the `(enforce)` mode
/// the kernel appends. `None` when AppArmor is absent or not enforcing.
#[must_use]
pub fn current_profile() -> Option<String> {
    std::fs::read_to_string(ATTR_CURRENT)
        .ok()?
        .split_whitespace()
        .next()
        .filter(|name| !name.is_empty())
        .map(str::to_owned)
}

/// Whether AppArmor took this process's capabilities away. Read from *inside*
/// the new user namespace: the transition happens as part of
/// `unshare(CLONE_NEWUSER)`, so the parent is still unconfined.
#[must_use]
pub fn capabilities_stripped() -> bool {
    current_profile().as_deref() == Some(USERNS_PROFILE)
}

/// Whether the host arms the restriction. Reported next to the profile check
/// because a host with `=1` and no `unprivileged_userns` profile loaded blocks
/// userspace namespaces outright instead of confining them.
#[must_use]
pub fn restrict_userns_enabled() -> bool {
    std::fs::read_to_string(RESTRICT_USERNS_SYSCTL).is_ok_and(|v| v.trim() == "1")
}

/// The commands that install the rendered profile.
///
/// Loading policy needs `CAP_MAC_ADMIN`, so this stays a one-time root step,
/// the same one the `apparmor` package performs for `bwrap`. The profile
/// is rendered into the message rather than read from disk so the advice still
/// works from a `cargo install`, a release tarball, or a Nix store path.
///
/// The block sits at column zero so it pastes into a shell as-is: an indented
/// heredoc terminator would not match and the paste would hang.
#[must_use]
pub fn install_instructions(binaries: &[&Path]) -> String {
    let mut msg = String::from(
        "  Install maki's AppArmor profile instead of weakening the host. This is\n  \
         how bwrap works too: its profile grants userns + capability, and\n  \
         kernel.apparmor_restrict_unprivileged_userns stays at 1.\n\n",
    );
    msg.push_str("sudo tee ");
    msg.push_str(PROFILE_PATH);
    msg.push_str(" > /dev/null <<'MAKI_EOF'\n");
    msg.push_str(&policy(binaries));
    msg.push_str("MAKI_EOF\n");
    msg.push_str(&format!("sudo apparmor_parser -r {PROFILE_PATH}\n\n"));
    msg
}

/// The AppArmor policy confining maki to the given binaries, granting the
/// capabilities and mount operations the sandbox needs inside its own user
/// namespace.
///
/// One profile with a comma-separated attachment list, because AppArmor
/// rejects two profiles sharing a name and every maki entry point needs the
/// same rules. The separator is a bare comma: a space after it is a parse
/// error on apparmor_parser 5.x.
///
/// The rule set mirrors the `bwrap-userns-restrict` profile AppArmor ships
/// for `bwrap` deliberately: it is the combination already proven to satisfy
/// `unshare`/`mount`/`pivot_root` under the restriction. File access stays broad because this profile is a
/// namespace capability grant, not the sandbox's isolation boundary -- that is
/// the mount namespace and `pivot_root` (see `namespace::setup_mounts`).
fn policy(binaries: &[&Path]) -> String {
    let mut policy = String::from(
        "# Generated by maki. Grants the sandbox the capabilities AppArmor's\n\
         # unprivileged_userns profile denies, so --sandbox works with\n\
         # kernel.apparmor_restrict_unprivileged_userns left at 1.\n\
         include <tunables/global>\n\n",
    );
    let attachments = binaries
        .iter()
        .map(|path| path.display().to_string())
        .collect::<Vec<_>>()
        .join(",");
    if attachments.is_empty() {
        return policy;
    }
    policy.push_str(&format!(
        "profile {PROFILE_NAME} {attachments} {{\n  \
         allow capability,\n  \
         allow userns,\n  \
         allow mount,\n  \
         allow umount,\n  \
         allow pivot_root,\n  \
         allow file rwlkm /{{**,}},\n  \
         allow network,\n  \
         allow unix,\n  \
         allow signal,\n  \
         allow mqueue,\n  \
         allow ptrace,\n  \
         allow dbus,\n  \
         allow io_uring,\n  \
         include if exists <local/{PROFILE_NAME}>\n}}\n"
    ));
    policy
}

/// The binaries to attach the profile to: the running executable plus the
/// sibling entry points that can spawn a sandbox.
///
/// Profile attachment is by absolute path and a re-installed maki lands
/// elsewhere, so this is resolved when the advice is printed, not at build
/// time. Only sibling paths are existence-checked; the running executable is
/// by definition the file we are executing from.
#[must_use]
pub fn sandbox_binaries() -> Vec<PathBuf> {
    let Ok(exe) = std::env::current_exe() else {
        return Vec::new();
    };
    let dir = exe.parent().map(Path::to_path_buf);
    let mut binaries = Vec::new();
    if let Some(dir) = &dir {
        binaries.extend(
            SANDBOX_ENTRY_POINTS
                .iter()
                .map(|name| dir.join(name))
                .filter(|path| path != &exe && path.is_file()),
        );
    }
    binaries.push(exe);
    binaries
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn policy_grants_the_operations_the_sandbox_needs() {
        let policy = policy(&[Path::new("/usr/local/bin/maki")]);
        assert!(policy.contains("profile maki-sandbox /usr/local/bin/maki {"));
        for rule in [
            "allow capability,",
            "allow userns,",
            "allow mount,",
            "allow umount,",
            "allow pivot_root,",
        ] {
            assert!(policy.contains(rule), "policy must grant '{rule}'");
        }
    }

    #[test]
    fn policy_names_every_binary_it_is_given() {
        let policy = policy(&[
            Path::new("/nix/store/abc-maki/bin/maki"),
            Path::new("/nix/store/abc-maki/bin/sandbox-diag"),
        ]);
        // One profile with several attachments: AppArmor refuses two profiles
        // that share a name, and a space after the attachment comma does not
        // parse.
        assert!(policy.contains(
            "profile maki-sandbox /nix/store/abc-maki/bin/maki,\
             /nix/store/abc-maki/bin/sandbox-diag {"
        ));
        assert_eq!(
            policy.matches("profile maki-sandbox ").count(),
            1,
            "entry points must share a single profile"
        );
    }

    #[test]
    fn policy_without_binaries_declares_no_profile() {
        // An attachmentless profile is a no-op, and a bare `profile maki-sandbox`
        // line does not compile, so the header alone is the only safe output.
        assert!(!policy(&[]).contains("profile maki-sandbox "));
    }

    #[test]
    fn install_instructions_are_a_pasteable_heredoc() {
        let instructions = install_instructions(&[Path::new("/usr/local/bin/maki")]);
        assert!(instructions.contains("sudo tee /etc/apparmor.d/maki-sandbox"));
        assert!(instructions.contains("profile maki-sandbox /usr/local/bin/maki {"));
        assert!(instructions.contains("sudo apparmor_parser -r /etc/apparmor.d/maki-sandbox"));
        // A heredoc terminator indented past column zero never matches, so the
        // pasted block would hang waiting for input.
        assert!(
            instructions.contains("\nMAKI_EOF\n"),
            "the terminator must start the line"
        );
        assert!(
            !instructions
                .lines()
                .skip(3)
                .any(|l| l.trim() == "MAKI_EOF" && l.len() != "MAKI_EOF".len()),
            "no indented terminator may be emitted"
        );
    }

    #[test]
    fn capabilities_stripped_tracks_the_reported_profile() {
        assert_eq!(
            capabilities_stripped(),
            current_profile().as_deref() == Some(USERNS_PROFILE)
        );
    }
}
