[package]
name = "maki-otel"
version.workspace = true
edition.workspace = true

[dependencies]
maki-config = { workspace = true }
isahc = { workspace = true }
serde_json = { workspace = true }
smol = { workspace = true }
flume = { workspace = true }
futures-lite = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true }
jiff = { workspace = true }
fastrand = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
