base_url = "/docs"
title = "Maki Docs"
compile_sass = true
build_search_index = false

[markdown.highlighting]
enabled = true
style = "inline"
light_theme = "maki-light"
dark_theme = "maki-dark"
extra_themes = ["extra/maki-light.json", "extra/maki-dark.json"]
